### ISSUE TITLE
The subscription cannot be used.

### ISSUE THREAD

**Issue by godfather216** [mermeroo/V2RAY-and-CLASH-Subscription-Links#2]
Hello, I used the subscription link you generated to import clashmeta shadowrocket. After testing, there is no network connection and I can't access the Internet. Please tell me how to use it. Thank you!

**Comment by mermeroo** [comment]
explain operation system and vpn client

**Comment by godfather216** [comment]
> explain operation system and vpn client 

ios  shadowrocket

**Comment by godfather216** [comment]
> > explain operation system and vpn client 
> 
> ios  shadowrocket. singbox
